#server:
##  port: 7001
##
##eureka:
##  instance:
##    hostname: localhsot #eureka服务端实例名称
##  client:
##    register-with-eureka: false #表示不像注册中心注册自己
##    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
##    service-url:
##      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端实例名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    enable-self-preservation: true #关闭Eureka自我保护机制（默认true）
    eviction-interval-timer-in-ms: 2000 #心跳包间隔改小方便测试