#微服务建议一定要写服务端口号和微服务名称
server:
  #端口号
  port: 8001

spring:
  application:
    #微服务名称
    name: cloud-provider-hystrix-payment

eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://localhost:7001/eureka/ # 入驻地址
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8001 #实例别名
    prefer-ip-address: true #访问路径可以显示IP地址
    #Eureka客户端向服务端发送心跳的时间间隔，单位是秒，（默认30秒）
    lease-renewal-interval-in-seconds: 5
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位秒（默认90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 10
